<?php

class PUPI_COMA_Options
{
    const META_SECRET = 1;
    const META_EMAIL = 2;
    const META_ACCOUNT = 3;
    const META_SITE_URL = 4;
    const META_PLUGIN = 5;
    const META_DO_NOT_IMPORT = 6;

    const OPTIONS = [
        'adsense_adunit_id' => [
            self::META_PLUGIN => true,
        ],
        'adsense_publisher_id' => [
            self::META_ACCOUNT => true,
            self::META_PLUGIN => true,
        ],
        'allow_anonymous_naming' => [],
        'allow_change_usernames' => [],
        'allow_close_own_questions' => [],
        'allow_close_questions' => [],
        'allow_login_email_only' => [],
        'allow_multi_answers' => [],
        'allow_no_category' => [],
        'allow_no_sub_category' => [],
        'allow_private_messages' => [],
        'allow_self_answer' => [],
        'allow_user_walls' => [],
        'allow_view_q_bots' => [],
        'approve_user_required' => [],
        'avatar_allow_gravatar' => [],
        'avatar_allow_upload' => [],
        'avatar_default_blobid' => [],
        'avatar_default_height' => [],
        'avatar_default_show' => [],
        'avatar_default_width' => [],
        'avatar_message_list_size' => [],
        'avatar_profile_size' => [],
        'avatar_q_list_size' => [],
        'avatar_q_page_a_size' => [],
        'avatar_q_page_c_size' => [],
        'avatar_q_page_q_size' => [],
        'avatar_store_size' => [],
        'avatar_users_size' => [],
        'block_bad_usernames' => [],
        'block_bad_words' => [],
        'block_ips_write' => [],
        'cache_acount' => [
            self::META_DO_NOT_IMPORT => true,
        ],
        'cache_ccount' => [
            self::META_DO_NOT_IMPORT => true,
        ],
        'cache_flaggedcount' => [
            self::META_DO_NOT_IMPORT => true,
        ],
        'cache_qcount' => [
            self::META_DO_NOT_IMPORT => true,
        ],
        'cache_queuedcount' => [
            self::META_DO_NOT_IMPORT => true,
        ],
        'cache_tagcount' => [
            self::META_DO_NOT_IMPORT => true,
        ],
        'cache_uapprovecount' => [
            self::META_DO_NOT_IMPORT => true,
        ],
        'cache_unaqcount' => [
            self::META_DO_NOT_IMPORT => true,
        ],
        'cache_unselqcount' => [
            self::META_DO_NOT_IMPORT => true,
        ],
        'cache_unupaqcount' => [
            self::META_DO_NOT_IMPORT => true,
        ],
        'cache_userpointscount' => [
            self::META_DO_NOT_IMPORT => true,
        ],
        'caching_catwidget_time' => [],
        'caching_driver' => [],
        'caching_enabled' => [],
        'caching_q_start' => [],
        'caching_q_time' => [],
        'caching_qlist_time' => [],
        'captcha_module' => [],
        'captcha_on_anon_post' => [],
        'captcha_on_feedback' => [],
        'captcha_on_register' => [],
        'captcha_on_reset_password' => [],
        'captcha_on_unapproved' => [],
        'captcha_on_unconfirmed' => [],
        'columns_tags' => [],
        'columns_users' => [],
        'comment_on_as' => [],
        'comment_on_qs' => [],
        'confirm_user_emails' => [],
        'confirm_user_required' => [],
        'custom_answer' => [],
        'custom_ask' => [],
        'custom_comment' => [],
        'custom_footer' => [],
        'custom_header' => [],
        'custom_home_content' => [],
        'custom_home_heading' => [],
        'custom_in_head' => [],
        'custom_register' => [],
        'custom_sidebar' => [],
        'custom_sidepanel' => [],
        'custom_welcome' => [],
        'db_version' => [],
        'do_ask_check_qs' => [],
        'do_close_on_select' => [],
        'do_complete_tags' => [],
        'do_count_q_views' => [],
        'do_example_tags' => [],
        'editor_for_as' => [],
        'editor_for_cs' => [],
        'editor_for_qs' => [],
        'email_privacy' => [],
        'enabled_plugins' => [],
        'event_logger_directory' => [
            self::META_PLUGIN => true,
        ],
        'event_logger_hide_header' => [
            self::META_PLUGIN => true,
        ],
        'event_logger_to_database' => [
            self::META_PLUGIN => true,
        ],
        'event_logger_to_files' => [
            self::META_PLUGIN => true,
        ],
        'extra_field_active' => [],
        'extra_field_display' => [],
        'extra_field_label' => [],
        'extra_field_prompt' => [],
        'facebook_app_id' => [
            self::META_ACCOUNT => true,
            self::META_PLUGIN => true,
        ],
        'facebook_app_secret' => [
            self::META_SECRET => true,
            self::META_PLUGIN => true,
        ],
        'feed_for_activity' => [],
        'feed_for_hot' => [],
        'feed_for_qa' => [],
        'feed_for_questions' => [],
        'feed_for_search' => [],
        'feed_for_tag_qs' => [],
        'feed_for_unanswered' => [],
        'feed_full_text' => [],
        'feed_number_items' => [],
        'feed_per_category' => [],
        'feedback_email' => [
            self::META_EMAIL => true,
        ],
        'feedback_enabled' => [],
        'flagging_hide_after' => [],
        'flagging_notify_every' => [],
        'flagging_notify_first' => [],
        'flagging_of_posts' => [],
        'follow_on_as' => [],
        'form_security_salt' => [
            self::META_SECRET => true,
        ],
        'from_email' => [
            self::META_EMAIL => true,
        ],
        'home_description' => [],
        'hot_weight_a_age' => [],
        'hot_weight_answers' => [],
        'hot_weight_q_age' => [],
        'hot_weight_views' => [],
        'hot_weight_votes' => [],
        'links_in_new_window' => [],
        'logo_height' => [],
        'logo_show' => [],
        'logo_url' => [
            self::META_SITE_URL => true,
        ],
        'logo_width' => [],
        'mailing_body' => [],
        'mailing_done_users' => [],
        'mailing_enabled' => [],
        'mailing_from_email' => [
            self::META_EMAIL => true,
        ],
        'mailing_from_name' => [],
        'mailing_last_timestamp' => [],
        'mailing_last_userid' => [],
        'mailing_per_minute' => [],
        'mailing_subject' => [],
        'mailing_total_users' => [],
        'match_ask_check_qs' => [],
        'match_example_tags' => [],
        'match_related_qs' => [
            self::META_PLUGIN => true,
        ],
        'max_copy_user_updates' => [],
        'max_len_q_title' => [],
        'max_num_q_tags' => [],
        'max_rate_ip_as' => [],
        'max_rate_ip_cs' => [],
        'max_rate_ip_flags' => [],
        'max_rate_ip_logins' => [],
        'max_rate_ip_messages' => [],
        'max_rate_ip_qs' => [],
        'max_rate_ip_registers' => [],
        'max_rate_ip_uploads' => [],
        'max_rate_ip_votes' => [],
        'max_rate_user_as' => [],
        'max_rate_user_cs' => [],
        'max_rate_user_flags' => [],
        'max_rate_user_messages' => [],
        'max_rate_user_qs' => [],
        'max_rate_user_uploads' => [],
        'max_rate_user_votes' => [],
        'max_store_user_updates' => [],
        'min_len_a_content' => [],
        'min_len_c_content' => [],
        'min_len_q_content' => [],
        'min_len_q_title' => [],
        'min_num_q_tags' => [],
        'minify_html' => [],
        'moderate_anon_post' => [],
        'moderate_by_points' => [],
        'moderate_edited_again' => [],
        'moderate_notify_admin' => [],
        'moderate_points_limit' => [],
        'moderate_unapproved' => [],
        'moderate_unconfirmed' => [],
        'moderate_update_time' => [],
        'moderate_users' => [],
        'mouseover_content_on' =>  [
            self::META_PLUGIN => true,
        ],
        'mouseover_content_max_len' =>  [
            self::META_PLUGIN => true,
        ],
        'nav_activity' => [],
        'nav_ask' => [],
        'nav_categories' => [],
        'nav_home' => [],
        'nav_hot' => [],
        'nav_qa_is_home' => [],
        'nav_qa_not_home' => [],
        'nav_questions' => [],
        'nav_tags' => [],
        'nav_unanswered' => [],
        'nav_users' => [],
        'neat_urls' => [],
        'notice_visitor' => [],
        'notice_welcome' => [],
        'notify_admin_q_post' => [],
        'notify_users_default' => [],
        'page_size_activity' => [],
        'page_size_ask_check_qs' => [],
        'page_size_ask_tags' => [],
        'page_size_home' => [],
        'page_size_hot_qs' => [],
        'page_size_pms' => [],
        'page_size_q_as' => [],
        'page_size_qs' => [],
        'page_size_related_qs' => [],
        'page_size_search' => [],
        'page_size_tag_qs' => [],
        'page_size_tags' => [],
        'page_size_una_qs' => [],
        'page_size_users' => [],
        'page_size_wall' => [],
        'pages_prev_next' => [],
        'permit_anon_view_ips' => [],
        'permit_anon_view_ips_points' => [],
        'permit_close_q' => [],
        'permit_close_q_points' => [],
        'permit_delete_hidden' => [],
        'permit_delete_hidden_points' => [],
        'permit_edit_a' => [],
        'permit_edit_a_points' => [],
        'permit_edit_c' => [],
        'permit_edit_c_points' => [],
        'permit_edit_q' => [],
        'permit_edit_q_points' => [],
        'permit_edit_silent' => [],
        'permit_edit_silent_points' => [],
        'permit_flag' => [],
        'permit_flag_points' => [],
        'permit_hide_show' => [],
        'permit_hide_show_points' => [],
        'permit_moderate' => [],
        'permit_moderate_points' => [],
        'permit_post_a' => [],
        'permit_post_a_points' => [],
        'permit_post_c' => [],
        'permit_post_c_points' => [],
        'permit_post_q' => [],
        'permit_post_q_points' => [],
        'permit_post_wall' => [],
        'permit_post_wall_points' => [],
        'permit_retag_cat' => [],
        'permit_retag_cat_points' => [],
        'permit_select_a' => [],
        'permit_select_a_points' => [],
        'permit_view_q_page' => [],
        'permit_view_new_users_page' => [],
        'permit_view_special_users_page' => [],
        'permit_view_voters_flaggers' => [],
        'permit_view_voters_flaggers_points' => [],
        'permit_vote_a' => [],
        'permit_vote_a_points' => [],
        'permit_vote_c' => [],
        'permit_vote_c_points' => [],
        'permit_vote_down' => [],
        'permit_vote_down_points' => [],
        'permit_vote_q' => [],
        'permit_vote_q_points' => [],
        'points_a_selected' => [],
        'points_a_voted_max_gain' => [],
        'points_a_voted_max_loss' => [],
        'points_base' => [],
        'points_c_voted_max_gain' => [],
        'points_c_voted_max_loss' => [],
        'points_multiple' => [],
        'points_per_a_voted' => [],
        'points_per_a_voted_down' => [],
        'points_per_a_voted_up' => [],
        'points_per_c_voted_down' => [],
        'points_per_c_voted_up' => [],
        'points_per_q_voted' => [],
        'points_per_q_voted_down' => [],
        'points_per_q_voted_up' => [],
        'points_post_a' => [],
        'points_post_q' => [],
        'points_q_voted_max_gain' => [],
        'points_q_voted_max_loss' => [],
        'points_select_a' => [],
        'points_to_titles' => [],
        'points_vote_down_a' => [],
        'points_vote_down_q' => [],
        'points_vote_on_a' => [],
        'points_vote_on_q' => [],
        'points_vote_up_a' => [],
        'points_vote_up_q' => [],
        'q_urls_remove_accents' => [],
        'q_urls_title_length' => [],
        'recalc_hotness_q_view' => [],
        'recaptcha_private_key' =>  [
            self::META_SECRET => true,
            self::META_PLUGIN => true,
        ],
        'recaptcha_public_key' =>   [
            self::META_ACCOUNT => true,
            self::META_PLUGIN => true,
        ],
        'register_notify_admin' => [],
        'register_terms' => [],
        'search_module' => [],
        'show_a_c_links' => [],
        'show_a_form_immediate' => [],
        'show_c_reply_buttons' => [],
        'show_compact_numbers' => [],
        'show_custom_answer' => [],
        'show_custom_ask' => [],
        'show_custom_comment' => [],
        'show_custom_footer' => [],
        'show_custom_header' => [],
        'show_custom_home' => [],
        'show_custom_in_head' => [],
        'show_custom_register' => [],
        'show_custom_sidebar' => [],
        'show_custom_sidepanel' => [],
        'show_custom_welcome' => [],
        'show_fewer_cs_count' => [],
        'show_fewer_cs_from' => [],
        'show_full_date_days' => [],
        'show_home_description' => [],
        'show_message_history' => [],
        'show_notice_visitor' => [],
        'show_notice_welcome' => [],
        'show_post_update_meta' => [],
        'show_register_terms' => [],
        'show_selected_first' => [],
        'show_url_links' => [],
        'show_user_points' => [],
        'show_user_titles' => [],
        'show_view_count_q_page' => [],
        'show_view_counts' => [],
        'show_when_created' => [],
        'site_language' => [],
        'site_maintenance' => [],
        'site_text_direction' => [],
        'site_theme' => [],
        'site_theme_mobile' => [],
        'site_title' => [],
        'site_url' => [
            self::META_SITE_URL => true,
        ],
        'smtp_active' => [],
        'smtp_address' => [
            self::META_SITE_URL => true,
        ],
        'smtp_authenticate' => [],
        'smtp_password' => [
            self::META_SECRET => true,
        ],
        'smtp_port' => [],
        'smtp_secure' => [],
        'smtp_username' => [
            self::META_ACCOUNT => true,
        ],
        'sort_answers_by' => [],
        'suspend_register_users' => [],
        'tag_separator_comma' => [],
        'tags_or_categories' => [],
        'use_microdata' => [],
        'votes_separated' => [],
        'voting_on_as' => [],
        'voting_on_cs' => [],
        'voting_on_q_page_only' => [],
        'voting_on_qs' => [],
        'wysiwyg_editor_upload_all' => [
            self::META_PLUGIN => true,
        ],
        'wysiwyg_editor_upload_images' => [
            self::META_PLUGIN => true,
        ],
        'wysiwyg_editor_upload_max_size' => [
            self::META_PLUGIN => true,
        ],
        'xml_sitemap_show_categories' => [
            self::META_PLUGIN => true,
        ],
        'xml_sitemap_show_category_qs' => [
            self::META_PLUGIN => true,
        ],
        'xml_sitemap_show_questions' => [
            self::META_PLUGIN => true,
        ],
        'xml_sitemap_show_tag_qs' => [
            self::META_PLUGIN => true,
        ],
        'xml_sitemap_show_users' => [
            self::META_PLUGIN => true,
        ],
    ];

    public static function getAllMetas(): array
    {
        return [
            self::META_SECRET,
            self::META_EMAIL,
            self::META_ACCOUNT,
            self::META_SITE_URL,
            self::META_PLUGIN,
        ];
    }
}
